maodified yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -15,6 +15,13 @@ lint:
     - python3 -m venv venv
     - echo "Virtual environment created"
     - ls -l venv
+    - | 
+      if [ -f venv/bin/activate ]; then 
+        echo "Activation script found";
+      else 
+        echo "Activation script not found"; 
+        exit 1;
+      fi
     - source venv/bin/activate
     - echo "Virtual environment activated"
     - pip install flake8
@@ -27,6 +34,13 @@ test:
     - python3 -m venv venv
     - echo "Virtual environment created"
     - ls -l venv
+    - | 
+      if [ -f venv/bin/activate ]; then 
+        echo "Activation script found";
+      else 
+        echo "Activation script not found"; 
+        exit 1;
+      fi
     - source venv/bin/activate
     - echo "Virtual environment activated"
     - pip install pytest
